Lineage pull request for: skeleton
cisagov/terraform-to-secrets pull request #2
Opened 2023-05-29 21:24 UTC by cisagovbot

# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-python-library.git`](https://github.com/cisagov/skeleton-python-library.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

## ✅ Pre-approval checklist ##

Remove any of the following that do not apply. If you're unsure about
any of these, don't hesitate to ask. We're here to help!

- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

Remove any of the following that do not apply. These boxes should
remain unchecked until the pull request has been approved.

- [ ] Bump major, minor, patch, or pre-release version [as
      appropriate](https://semver.org/#semantic-versioning-specification-semver)
      via the `bump_version.sh` script *if* this repository is
      versioned *and* the changes in this PR [warrant a version
      bump](https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api).
- [ ] Finalize version.

## ✅ Post-merge checklist ##

Remove any of the following that do not apply.

- [ ] Create a release.

---

> **Note**
> You are seeing this because one of this repository's maintainers has
> configured [Lineage] to open pull requests.

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

2023-06-12 17:05 UTC, jsf9k requested changes
I have one minor change to request.

2023-06-12 17:05 UTC, jsf9k commented on .github/dependabot.yml
> +      # - dependency-name: actions/upload-artifact
I think these lines should be uncommented:
```suggestion
      # Managed by cisagov/skeleton-python-library
      - dependency-name: actions/download-artifact
      - dependency-name: actions/upload-artifact
```

2023-06-12 17:13 UTC, dav3r approved these changes

2023-12-20 19:20 UTC, jsf9k requested changes
[The issue I brought up in my original review](https://github.com/cisagov/terraform-to-secrets/pull/2/files#r1226974260) still stands.

2024-08-08 18:30 UTC, jsf9k commented on .github/dependabot.yml
> +      # - dependency-name: actions/upload-artifact
Ah, this is one where the repo still has a `first-commits` branch.

2024-08-08 18:34 UTC, jsf9k approved these changes

2024-08-08 18:35 UTC, merged